import { StorageOrientation } from "../components/StorageOrientation";
import { useEffect, useMemo, useRef, useState, type CSSProperties } from 'react';
import { CATALOG_OBJECTS, categoryDisplayName, getCatalogObject, quantityLabel, searchCatalog } from '../lib/catalog';
import { cloneGroup, newCatalogGroup, newCustomGroup, type DrawerState, type ItemGroup } from '../lib/state';
import { placedCols, placedRows, type ContainerSpec, type PlacedContainer } from '../lib/types';
import { fitGrid } from '../lib/gridLayout';
import { tileBaseplates } from '../lib/baseplateTiler';
import { download3mf } from '../api';
import { arrange, colorFor, downloadJSON, groupId, minHeight, reconcile, specsForGroups, validPlacement, type Layout } from './model';
import { Plan3D } from './Plan3D';
import './place.css';

interface Props { drawer: DrawerState; groups: ItemGroup[]; onChange:(g:ItemGroup[])=>void; onMeasure:()=>void }
function NumberField({value,min=1,max=999,onChange,label}:{value:number;min?:number;max?:number;onChange:(n:number)=>void;label:string}){
  const [draft,setDraft]=useState(String(value));useEffect(()=>setDraft(String(value)),[value]);
  return <label className="place-field">{label}<input type="number" min={min} max={max} value={draft} onChange={e=>setDraft(e.target.value)} onBlur={()=>{const n=Number(draft);if(Number.isFinite(n)&&n>=min&&n<=max)onChange(Math.round(n));else setDraft(String(value));}} onKeyDown={e=>{if(e.key==='Enter')e.currentTarget.blur();}}/></label>;
}
function PocketPattern({s}:{s:ContainerSpec}){
  const w=s.length_u*42,h=s.width_u*42;
  return <svg className="place-pattern" viewBox={`0 0 ${w} ${h}`} preserveAspectRatio="none" aria-hidden="true">
    {s.kind==='bin'?<>{Array.from({length:Math.max(0,s.length_div-1)},(_,i)=><path key={'x'+i} d={`M ${w*(i+1)/s.length_div} 4 V ${h-4}`}/>)}{Array.from({length:Math.max(0,s.width_div-1)},(_,i)=><path key={'y'+i} d={`M 4 ${h*(i+1)/s.width_div} H ${w-4}`}/>)}</>:s.kind==='spool'?<><circle cx={w/2} cy={h/2} r={Math.min(w,h)*.38}/><circle cx={w/2} cy={h/2} r={Math.min(w,h)*.15}/></>:Array.from({length:Math.min(200,s.pocket_rows*s.pocket_cols)},(_,i)=>{const x=3+(w-6)*((i%s.pocket_cols)+.5)/s.pocket_cols,y=3+(h-6)*(Math.floor(i/s.pocket_cols)+.5)/s.pocket_rows;return s.kind==='rect_pockets'?<rect key={i} x={x-s.pocket_length_mm/2} y={y-s.pocket_width_mm/2} width={s.pocket_length_mm} height={s.pocket_width_mm} rx="1"/>:<circle key={i} cx={x} cy={y} r={s.pocket_diam_mm/2}/>;})}
  </svg>;
}
export function Place({drawer,groups,onChange,onMeasure}:Props){
  const grid=useMemo(()=>fitGrid(drawer.widthMm,drawer.heightMm),[drawer.widthMm,drawer.heightMm]);
  const generated=useMemo(()=>specsForGroups(groups,drawer.depthMm,grid.cols,grid.rows),[groups,drawer.depthMm,grid.cols,grid.rows]);
  const [layout,setLayout]=useState<Layout>(()=>arrange(generated.specs,grid.cols,grid.rows));
  const [history,setHistory]=useState<Layout[]>([]),[future,setFuture]=useState<Layout[]>([]);
  const [selected,setSelected]=useState(''),[selectedGroup,setSelectedGroup]=useState(groups[0]?.id??'');
  const [query,setQuery]=useState(''),[highlight,setHighlight]=useState(0),[view,setView]=useState<'2d'|'3d'>('3d');
  const [message,setMessage]=useState('Add an object, set its quantity, and choose how it sits.');
  const [mobileItems,setMobileItems]=useState(false),[zoom,setZoom]=useState(100),[busy,setBusy]=useState(false);
  const [ghost,setGhost]=useState<PlacedContainer|null>(null),[dragging,setDragging]=useState(false);
  const board=useRef<HTMLDivElement>(null),search=useRef<HTMLInputElement>(null);
  const drag=useRef<{p:PlacedContainer;x:number;y:number;cellX:number;cellY:number;candidate:PlacedContainer}|null>(null);
  useEffect(()=>{setLayout(old=>reconcile(generated.specs,old,grid.cols,grid.rows,generated.maxHeight,generated.heightLimits));setHistory([]);setFuture([]);},[generated,grid.cols,grid.rows]);
  useEffect(()=>{if(!groups.some(g=>g.id===selectedGroup))setSelectedGroup(groups[0]?.id??'');},[groups,selectedGroup]);
  const allSpecs=[...layout.placed.map(p=>p.spec),...layout.unplaced];
  const selectedSpec=allSpecs.find(s=>s.id===selected);
  const selectedPlacement=layout.placed.find(p=>p.spec.id===selected);
  const results=useMemo(()=>searchCatalog(query),[query]);
  const commit=(next:Layout,text:string)=>{setHistory(h=>[...h.slice(-39),layout]);setFuture([]);setLayout(next);setMessage(text);};
  const choose=(id:string)=>{setSelected(id);setSelectedGroup(groupId(id));};
  const updateGroup=(g:ItemGroup)=>{onChange(groups.map(old=>old.id===g.id?g:old));};
  const selectGroup=(id:string)=>{setSelectedGroup(id);setSelected(allSpecs.find(s=>groupId(s.id)===id)?.id??'');};
  const add=(id?:string)=>{const obj=id?getCatalogObject(id):null,g=obj?newCatalogGroup(obj.id,obj.name):newCustomGroup(query.trim()||'Custom object');onChange([...groups,g]);setSelectedGroup(g.id);setSelected(`${g.id}:0:0`);setQuery('');setHighlight(0);setMessage(`${g.name} added. Existing placements are kept where they still fit.`);search.current?.focus();};
  const rotate=()=>{if(!selectedPlacement)return;const p={...selectedPlacement,rotated:!selectedPlacement.rotated};if(!validPlacement(p,layout.placed,grid.cols,grid.rows)){setMessage('There is not enough room to rotate here. Move the bin to an open space first.');return;}commit({...layout,placed:layout.placed.map(old=>old.spec.id===p.spec.id?p:old)},`${p.spec.name} rotated 90°.`);};
  const setHeight=(height:number)=>{if(!selectedSpec)return;if(!Number.isInteger(height)||height<Math.max(minHeight(selectedSpec),generated.specs.find(s=>s.id===selected)?.height_u??2)||height>(generated.heightLimits[selected]??generated.maxHeight))return;const change=(s:ContainerSpec)=>s.id===selected?{...s,height_u:height}:s;commit({placed:layout.placed.map(p=>({...p,spec:change(p.spec)})),unplaced:layout.unplaced.map(change)},`${selectedSpec.name} height set to ${height*7} mm.`);};
  const undo=()=>{if(!history.length)return;setFuture(f=>[layout,...f]);setLayout(history[history.length-1]);setHistory(h=>h.slice(0,-1));setMessage('Previous layout restored.');};
  const redo=()=>{if(!future.length)return;setHistory(h=>[...h,layout]);setLayout(future[0]);setFuture(f=>f.slice(1));setMessage('Change reapplied.');};
  const auto=()=>{const next=arrange(allSpecs,grid.cols,grid.rows,layout);commit(next,next.unplaced.length?`Best layout found: ${next.unplaced.length} bins still need space.`:'Auto arranged. Undo brings back your manual layout.');};
  const total=grid.cols*grid.rows;
  const export3mf=async()=>{if(!layout.placed.length||layout.unplaced.length||generated.skipped.length||generated.invalidNames.length)return;setBusy(true);try{const blob=await download3mf(layout.placed,tileBaseplates(grid.cols,grid.rows));const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='boxable.3mf';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);setMessage('3MF downloaded. Check total height and fit in your slicer.');}catch(e){setMessage(e instanceof Error?`3MF could not be built. ${e.message}`:'3MF could not be built.');}finally{setBusy(false);}};
  const save=()=>{if(generated.invalidNames.length)return;downloadJSON({version:1,drawer:{widthMm:drawer.widthMm,heightMm:drawer.heightMm,depthMm:drawer.depthMm},groups,items:layout.placed,unplaced:layout.unplaced,baseplates:tileBaseplates(grid.cols,grid.rows)});setMessage('Drawer plan saved, including positions, rotation, and height.');};
  if(!total)return <section className="panel"><h2>Start with your drawer.</h2><p>Enter dimensions that fit at least one 42 × 42 mm cell.</p><button className="btn" onClick={onMeasure}>Measure drawer</button></section>;
  return <div className="place-workspace">
    <div className="place-mobile-bar"><button type="button" className="place-button" onClick={()=>setMobileItems(!mobileItems)}>{mobileItems?'Hide':'Add / edit'} things · {groups.length}</button><span>{layout.placed.length} bins placed</span></div>
    <aside className={`place-sidebar ${mobileItems?'is-open':''}`} aria-label="Your things">
      <div className="place-sidebar-head"><p className="place-kicker">01 / YOUR THINGS</p><h2>What needs a home?</h2><p>Object, quantity, orientation. We’ll handle the fit.</p></div>
      <div className="place-search"><label htmlFor="place-search">Find an object</label><input id="place-search" ref={search} role="combobox" aria-expanded={!!query.trim()} aria-controls="place-results" aria-autocomplete="list" aria-activedescendant={query.trim()&&results[highlight]?`place-result-${highlight}`:undefined} placeholder="Batteries, cables, pens…" value={query} onChange={e=>{setQuery(e.target.value);setHighlight(0);}} onKeyDown={e=>{if(e.key==='Escape')setQuery('');if(e.key==='ArrowDown'){e.preventDefault();setHighlight(h=>Math.min(results.length-1,h+1));}if(e.key==='ArrowUp'){e.preventDefault();setHighlight(h=>Math.max(0,h-1));}if(e.key==='Enter'&&query.trim()){e.preventDefault();add(results[highlight]?.id);}}}/>
        {query.trim()&&<div className="place-search-menu"><div id="place-results" role="listbox">{results.map((o,i)=><button type="button" role="option" id={`place-result-${i}`} aria-selected={i===highlight} key={o.id} onMouseEnter={()=>setHighlight(i)} onClick={()=>add(o.id)}><strong>{o.name}</strong><span>{categoryDisplayName(o.category)}</span></button>)}</div><button className="place-custom-result" type="button" onClick={()=>add()}>+ Add “{query.trim()}” as custom</button></div>}
      </div>
      <button type="button" className="place-custom" onClick={()=>add()}>+ Custom object</button>
      <div className="place-list-title"><span>YOUR OBJECTS</span><span>{groups.length.toString().padStart(2,'0')}</span></div>
      <div className="place-group-list">{groups.length===0?<p className="place-empty">Search for your first object above.</p>:groups.map(g=>{const bins=allSpecs.filter(s=>groupId(s.id)===g.id),missing=layout.unplaced.filter(s=>groupId(s.id)===g.id).length,isActive=selectedGroup===g.id;return <div key={g.id} className={`place-group ${isActive?'active':''}`}>
        <button type="button" className="place-group-select" aria-expanded={isActive} onClick={()=>selectGroup(g.id)}><span className="place-swatch" style={{background:colorFor(g.id)}}/><span><strong>{g.name}</strong><small>{g.count} {g.mode==='catalog'?quantityLabel(getCatalogObject(g.objectId)?.storage.quantity_mode??'individual'):'items'} · {bins.length} {bins.length===1?'bin':'bins'}{missing?' · needs space':''}</small></span><span aria-hidden="true">{isActive?'−':'+'}</span></button>
        {isActive&&<div className="place-group-editor"><label className="place-field">Object<input value={g.name} required maxLength={80} aria-invalid={!g.name.trim()} aria-describedby={`object-name-help-${g.id}`} onChange={e=>updateGroup({...g,name:e.target.value})} onBlur={()=>{if(g.name!==g.name.trim())updateGroup({...g,name:g.name.trim()});}}/></label><p id={`object-name-help-${g.id}`} className="place-small">{g.name.trim()?"Printed on each container for this object.":"Enter an object name to save or download your layout."}</p><div className="place-count"><span>Quantity</span><div><button type="button" aria-label={`Remove one ${g.name}`} disabled={g.count<=1} onClick={()=>updateGroup({...g,count:g.count-1})}>−</button><NumberField label="Count" value={g.count} onChange={count=>updateGroup({...g,count})}/><button type="button" aria-label={`Add one ${g.name}`} disabled={g.count>=999} onClick={()=>updateGroup({...g,count:g.count+1})}>+</button></div></div>
          <StorageOrientation group={g} onChange={next=>{updateGroup(next);setMessage(`${g.name}: ${next.storageOrientation==='flat'?'horizontal storage':'vertical storage'} selected. Container sizes updated.`);}}/>
          {selectedSpec&&groupId(selectedSpec.id)===g.id&&<details className="place-sidebar-adjust"><summary>Adjust selected container</summary><button type="button" className="place-button" disabled={!selectedPlacement} onClick={rotate}>↻ Rotate 90°</button><label className="place-field">Box height<select value={selectedSpec.height_u} onChange={e=>setHeight(Number(e.target.value))}>{Array.from({length:Math.max(0,(generated.heightLimits[selected]??generated.maxHeight)-Math.max(minHeight(selectedSpec),generated.specs.find(s=>s.id===selected)?.height_u??2)+1)},(_,i)=>i+Math.max(minHeight(selectedSpec),generated.specs.find(s=>s.id===selected)?.height_u??2)).map(u=><option key={u} value={u}>{u*7} mm</option>)}</select></label></details>}
          {g.mode==='custom'&&<><p className="place-small">Object dimensions (mm)</p><div className="place-dimensions"><NumberField label="Length" value={g.lengthMm} max={500} onChange={lengthMm=>updateGroup({...g,lengthMm})}/><NumberField label="Width" value={g.widthMm} max={500} onChange={widthMm=>updateGroup({...g,widthMm})}/><NumberField label="Height" value={g.heightMm} max={140} onChange={heightMm=>updateGroup({...g,heightMm})}/></div></>}
          {g.mode==='catalog'&&getCatalogObject(g.objectId)?.generation.support_level==='fallback'&&<p className="place-small">Uses a simple fitted container.</p>}
          <div className="place-group-actions"><button type="button" onClick={()=>{const copy=cloneGroup(g);onChange([...groups,copy]);setSelectedGroup(copy.id);setSelected('');}}>Duplicate</button><button type="button" onClick={()=>{onChange(groups.filter(x=>x.id!==g.id));setMessage(`${g.name} removed.`);}}>Remove</button></div>
        </div>}
      </div>})}</div>
      <div className="place-catalog-note">{CATALOG_OBJECTS.length} objects in the catalog.<br/>Check estimated sizes against your things.</div>
    </aside>
    <section className="place-plan" aria-label="Print plan">
      <div className="place-plan-header"><div><p className="place-kicker">02 / YOUR DRAWER</p><h2>Everything in its place.</h2></div><button type="button" className="place-auto" disabled={!allSpecs.length} onClick={auto}>Auto arrange <span aria-hidden="true">↗</span></button></div>
      <div className="place-tools"><div className="place-view-switch" role="group" aria-label="Plan view"><button type="button" aria-pressed={view==='2d'} onClick={()=>setView('2d')}>Top view</button><button type="button" aria-pressed={view==='3d'} onClick={()=>setView('3d')}>3D preview</button></div><div className="place-tool-actions"><button type="button" className="place-button" aria-label="Undo layout change" disabled={!history.length} onClick={undo}>↶ Undo</button><button type="button" className="place-button" aria-label="Redo layout change" disabled={!future.length} onClick={redo}>↷</button>{view==='2d'&&<><button type="button" className="place-button" aria-label="Zoom out" disabled={zoom<=75} onClick={()=>setZoom(z=>z-25)}>−</button><button type="button" className="place-button place-zoom" onClick={()=>setZoom(100)} aria-label="Fit drawer to view">{zoom}%</button><button type="button" className="place-button" aria-label="Zoom in" disabled={zoom>=200} onClick={()=>setZoom(z=>z+25)}>+</button></>}</div></div>
      {(generated.skipped.length>0||layout.unplaced.length>0)&&<div className="place-warning" role="status">{generated.skipped.length>0&&<span>Doesn’t fit with 1 cm of roof clearance: {generated.skipped.join(', ')}. Try Horizontal, fewer objects, or check your measurements. </span>}{layout.unplaced.length>0&&<span>{layout.unplaced.length} bins need space. Try Auto arrange, reduce quantities, or change drawers.</span>}</div>}
      {!!layout.unplaced.length&&<div className="place-unplaced"><strong>Waiting for space</strong>{layout.unplaced.map(s=><button type="button" className="place-button" key={s.id} onClick={()=>choose(s.id)}>{s.name} · {s.length_u}×{s.width_u}</button>)}</div>}
      <div className={message.startsWith('3MF could not be built')?'place-warning':'place-sr-only'} role="status" aria-live="polite">{message}</div>
      <div className="place-canvas-wrap" title={view==='2d'?'Drag to move · R to rotate · Arrow keys to nudge':'Drag to orbit · Scroll to zoom · Click a bin to select'}>
        {view==='2d'?<div className="place-canvas-scroll"><div className="place-drawer-shell" style={{width:`${zoom}%`,maxWidth:zoom===100?'760px':'none'}}><div className="place-ruler">{drawer.widthMm} mm <span>← drawer width →</span></div><div ref={board} className={`place-board ${dragging?'dragging':''}`} style={{aspectRatio:`${grid.cols}/${grid.rows}`,'--cell-x':`${100/grid.cols}%`,'--cell-y':`${100/grid.rows}%`} as CSSProperties} aria-label={`${grid.cols} by ${grid.rows} drawer grid`}>
          {layout.placed.map(p=><button type="button" key={p.spec.id} data-bin={p.spec.id} className={`place-bin ${selected===p.spec.id?'selected':''} ${dragging&&ghost?.spec.id===p.spec.id?'origin':''}`} aria-pressed={selected===p.spec.id} aria-label={`${p.spec.name}, ${placedCols(p)} by ${placedRows(p)} cells, ${p.spec.height_u*7} millimeters tall. Use arrow keys to move, R to rotate.`} style={{left:`${p.col/grid.cols*100}%`,top:`${p.row/grid.rows*100}%`,width:`${placedCols(p)/grid.cols*100}%`,height:`${placedRows(p)/grid.rows*100}%`,'--bin-color':colorFor(p.spec.id)} as CSSProperties}
            onClick={()=>choose(p.spec.id)} onPointerDown={e=>{if(e.button!==0)return;choose(p.spec.id);const rect=board.current!.getBoundingClientRect();drag.current={p,x:e.clientX,y:e.clientY,cellX:rect.width/grid.cols,cellY:rect.height/grid.rows,candidate:p};e.currentTarget.setPointerCapture(e.pointerId);}}
            onPointerMove={e=>{const d=drag.current;if(!d||d.p.spec.id!==p.spec.id)return;if(Math.hypot(e.clientX-d.x,e.clientY-d.y)<3)return;setDragging(true);d.candidate={...d.p,col:d.p.col+Math.round((e.clientX-d.x)/d.cellX),row:d.p.row+Math.round((e.clientY-d.y)/d.cellY)};setGhost(d.candidate);}}
            onPointerUp={()=>{const d=drag.current;drag.current=null;setGhost(null);setDragging(false);if(!d)return;if(d.candidate.col===d.p.col&&d.candidate.row===d.p.row)return;if(validPlacement(d.candidate,layout.placed,grid.cols,grid.rows))commit({...layout,placed:layout.placed.map(old=>old.spec.id===p.spec.id?d.candidate:old)},`${p.spec.name} moved.`);else setMessage('That space is blocked. Your bin stayed in its previous position.');}}
            onPointerCancel={()=>{drag.current=null;setGhost(null);setDragging(false);}}
            onKeyDown={e=>{if(e.key.toLowerCase()==='r'){e.preventDefault();rotate();return;}const delta=({ArrowLeft:[-1,0],ArrowRight:[1,0],ArrowUp:[0,-1],ArrowDown:[0,1]} as Record<string,number[]>)[e.key];if(!delta)return;e.preventDefault();choose(p.spec.id);const next={...p,col:p.col+delta[0],row:p.row+delta[1]};if(validPlacement(next,layout.placed,grid.cols,grid.rows))commit({...layout,placed:layout.placed.map(old=>old.spec.id===p.spec.id?next:old)},`${p.spec.name} moved.`);else setMessage('That space is blocked.');}}
            onFocus={()=>choose(p.spec.id)}>
            <div className="place-pattern-wrap" style={p.rotated?{width:`${p.spec.length_u/p.spec.width_u*100}%`,height:`${p.spec.width_u/p.spec.length_u*100}%`,transform:'rotate(90deg)',transformOrigin:'0 0',left:'100%'}:undefined}><PocketPattern s={p.spec}/></div><span className="place-bin-label">{p.spec.name}</span><span className="place-bin-size">{placedCols(p)} × {placedRows(p)}</span>
          </button>)}
          {ghost&&<div className={`place-drag-ghost ${validPlacement(ghost,layout.placed,grid.cols,grid.rows)?'valid':'invalid'}`} style={{left:`${ghost.col/grid.cols*100}%`,top:`${ghost.row/grid.rows*100}%`,width:`${placedCols(ghost)/grid.cols*100}%`,height:`${placedRows(ghost)/grid.rows*100}%`}}>{validPlacement(ghost,layout.placed,grid.cols,grid.rows)?'Place here':'Blocked'}</div>}
          {!layout.placed.length&&<div className="place-board-empty">Your drawer starts here.<br/><span>Add an object to see its bin.</span></div>}
        </div><div className="place-front">FRONT OF DRAWER <span>↓</span></div></div></div>:<Plan3D placed={layout.placed} cols={grid.cols} rows={grid.rows} selected={selected} onSelect={choose} drawerWidth={drawer.widthMm} drawerLength={drawer.heightMm} drawerHeight={drawer.depthMm}/>}
      </div>
      <div className="place-bottom-actions"><button type="button" className="place-button" onClick={save} disabled={!!generated.invalidNames.length}>Save layout</button><button type="button" className="place-primary" onClick={()=>void export3mf()} disabled={busy||!layout.placed.length||!!layout.unplaced.length||!!generated.skipped.length||!!generated.invalidNames.length}>{busy?'Building…':'Download 3MF'} <span aria-hidden="true">↓</span></button></div>
    </section>
  </div>;
}
