// @vitest-environment jsdom
import { cleanup,fireEvent,render,screen,waitFor } from '@testing-library/react';
import { afterEach,beforeEach,it,expect,vi } from 'vitest';
import { Auth } from './Auth';
const mocks=vi.hoisted(()=>({signUp:vi.fn(),signInWithPassword:vi.fn(),resetPasswordForEmail:vi.fn(),resend:vi.fn(),updateUser:vi.fn(),signInWithOAuth:vi.fn()}));
vi.mock('./client',()=>({supabase:{},client:()=>({auth:mocks}),callbackURL:()=> 'http://localhost:5173/'}));
beforeEach(()=>{for(const mock of Object.values(mocks))mock.mockReset().mockResolvedValue({error:null});});
afterEach(cleanup);
function view(recovery=false){const before=vi.fn().mockResolvedValue(undefined),close=vi.fn(),recovered=vi.fn();render(<Auth onBeforeAuth={before} onClose={close} onRecovered={recovered} recovery={recovery}/>);return{before,close,recovered};}
it('registers with name, email, password and requires confirmation',async()=>{view();fireEvent.click(screen.getByRole('button',{name:'Create an account'}));fireEvent.change(screen.getByLabelText('Your name'),{target:{value:'Julian'}});fireEvent.change(screen.getByLabelText('Email'),{target:{value:'julian@example.com'}});const password=screen.getByLabelText('Password');expect(password.getAttribute('minlength')).toBe('15');expect(password.getAttribute('autocomplete')).toBe('new-password');fireEvent.change(password,{target:{value:'a sufficiently long passphrase'}});fireEvent.submit(password.closest('form')!);await waitFor(()=>expect(mocks.signUp).toHaveBeenCalledWith({email:'julian@example.com',password:'a sufficiently long passphrase',options:{data:{display_name:'Julian'},emailRedirectTo:'http://localhost:5173/'}}));expect(await screen.findByRole('heading',{name:'Check your inbox.'})).toBeTruthy();});
it('uses generic failure messages and clears failed passwords',async()=>{mocks.signInWithPassword.mockResolvedValue({error:new Error('Account exists')});view();fireEvent.change(screen.getByLabelText('Email'),{target:{value:'person@example.com'}});fireEvent.change(screen.getByLabelText('Password'),{target:{value:'wrong'}});fireEvent.submit(screen.getByLabelText('Password').closest('form')!);await waitFor(()=>expect(screen.getByRole('status').textContent).toContain('Unable to complete'));expect((screen.getByLabelText('Password') as HTMLInputElement).value).toBe('');expect(screen.queryByText('Account exists')).toBeNull();});
it('keeps guest work available when an unverified password account tries to sign in',async()=>{mocks.signInWithPassword.mockResolvedValue({error:Object.assign(new Error('Email not confirmed'),{code:'email_not_confirmed'})});view();fireEvent.change(screen.getByLabelText('Email'),{target:{value:'person@example.com'}});fireEvent.change(screen.getByLabelText('Password'),{target:{value:'a sufficiently long passphrase'}});fireEvent.submit(screen.getByLabelText('Password').closest('form')!);expect(await screen.findByRole('heading',{name:'Check your inbox.'})).toBeTruthy();expect(screen.getByRole('status').textContent).toContain('guest work');});
it('preserves work before Google redirect and requests identity scopes only',async()=>{const {before}=view();fireEvent.click(screen.getByRole('button',{name:/Continue with Google/}));await waitFor(()=>expect(mocks.signInWithOAuth).toHaveBeenCalledWith({provider:'google',options:{redirectTo:'http://localhost:5173/',scopes:'openid email profile'}}));expect(before.mock.invocationCallOrder[0]).toBeLessThan(mocks.signInWithOAuth.mock.invocationCallOrder[0]);});
it('offers generic recovery and resend-confirmation flows',async()=>{view();fireEvent.click(screen.getByRole('button',{name:'Forgot password'}));fireEvent.change(screen.getByLabelText('Email'),{target:{value:'person@example.com'}});fireEvent.submit(screen.getByLabelText('Email').closest('form')!);await waitFor(()=>expect(mocks.resetPasswordForEmail).toHaveBeenCalled());expect(screen.getByRole('status').textContent).toContain('If this address has an account');fireEvent.click(screen.getByRole('button',{name:'Verify email'}));fireEvent.submit(screen.getByLabelText('Email').closest('form')!);await waitFor(()=>expect(mocks.resend).toHaveBeenCalledWith({type:'signup',email:'person@example.com',options:{emailRedirectTo:'http://localhost:5173/'}}));});
it('updates a password through a recovery session',async()=>{const {recovered}=view(true);fireEvent.change(screen.getByLabelText('Password'),{target:{value:'another long passphrase'}});fireEvent.submit(screen.getByLabelText('Password').closest('form')!);await waitFor(()=>expect(mocks.updateUser).toHaveBeenCalledWith({password:'another long passphrase'}));expect(recovered).toHaveBeenCalled();});
