import { useEffect, useState } from 'react';
import type { User } from '@supabase/supabase-js';
import { client } from './client';
import { deleteDrawer, listDrawers, photoFile, renameDrawer, type DrawerRow } from './repository';
function DrawerPhoto({path}:{path:string|null}){
 const [url,setURL]=useState('');
 useEffect(()=>{let active=true,objectURL='';setURL('');if(path)void photoFile(path).then(file=>{if(active){objectURL=URL.createObjectURL(file);setURL(objectURL);}}).catch(()=>{});return()=>{active=false;if(objectURL)URL.revokeObjectURL(objectURL);};},[path]);
 return url?<img src={url} alt=""/>:<div className="drawer-card-placeholder" aria-hidden="true">▦</div>;
}
export function Library({user,onOpen,onNew,onDeleted,currentId,currentDirty,currentRevision}:{user:User;onOpen:(row:DrawerRow)=>Promise<void>;onNew:()=>void;onDeleted:(id:string)=>void;currentId:string|null;currentDirty:boolean;currentRevision:number}){
 const [rows,setRows]=useState<DrawerRow[]>([]),[loading,setLoading]=useState(true),[query,setQuery]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false),[name,setName]=useState(''),[revision,setRevision]=useState(0);
 const [editing,setEditing]=useState<DrawerRow|null>(null),[drawerName,setDrawerName]=useState('');
 useEffect(()=>{let active=true;setLoading(true);void listDrawers().then(rows=>{if(active)setRows(rows);}).catch(()=>{if(active)setError('Your drawers could not be loaded. Try again.');}).finally(()=>{if(active)setLoading(false);});return()=>{active=false;};},[revision,currentRevision]);
 useEffect(()=>{let active=true;void client().from('profiles').select('display_name').eq('id',user.id).single().then(({data})=>{if(active)setName(data?.display_name??'');});return()=>{active=false;};},[user.id]);
 const action=async(fn:()=>Promise<void>)=>{setBusy(true);setError('');try{await fn();setRevision(v=>v+1);}catch(e){setError(e instanceof Error?e.message:'That change could not be saved. Please try again.');}finally{setBusy(false);}};
 return <section className="drawer-library"><div className="library-heading"><div><p className="account-eyebrow">A LITTLE ORDER, ALL YOURS</p><h1>My drawers<span aria-hidden="true">✳</span></h1><p>Pick up where you left off. Make room for something new.</p></div><button className="btn" onClick={onNew} disabled={busy}>+ New drawer</button></div>
 <details className="profile-settings"><summary>Your account · {user.email}</summary><form onSubmit={e=>{e.preventDefault();void action(async()=>{const {error}=await client().from('profiles').update({display_name:name.trim()}).eq('id',user.id);if(error)throw error;});}}><label>Your name<input required maxLength={80} value={name} onChange={e=>setName(e.target.value)}/></label><button className="place-button" disabled={busy||!name.trim()}>Save name</button><p>Your email is managed securely by your sign-in provider.</p></form></details>
 <div className="library-search"><label htmlFor="drawer-search">Find a drawer</label><input id="drawer-search" type="search" placeholder="Kitchen, desk, workshop…" value={query} onChange={e=>setQuery(e.target.value)}/><span>{rows.length} {rows.length===1?'drawer':'drawers'}</span></div>
 {error&&<div role="alert" className="account-notice">{error} <button onClick={()=>setRevision(v=>v+1)}>Retry</button></div>}
 {loading?<p role="status">Finding your drawers…</p>:rows.length===0?<div className="library-empty"><img src="/brand/boxie.webp" alt=""/><h2>Everything starts with one drawer.</h2><p>Measure it, arrange it, and we’ll keep your plan safe here.</p><button className="btn" onClick={onNew}>Create my first drawer ↗</button></div>:<div className="drawer-cards">{rows.filter(r=>r.name.toLowerCase().includes(query.toLowerCase())).map(row=><article className="drawer-card" key={row.id}><button className="drawer-card-open" disabled={busy} onClick={()=>void action(()=>onOpen(row))}><DrawerPhoto path={row.photo_path}/><div><h2>{row.name}</h2><p>{row.document?.drawer?.widthMm??0} × {row.document?.drawer?.heightMm??0} mm</p><small>Saved {new Date(row.updated_at).toLocaleString()}</small><span className="drawer-card-arrow" aria-hidden="true">↗</span></div></button><div className="drawer-card-actions"><button disabled={busy||row.id===currentId} title={row.id===currentId?'Rename the open drawer in the planner':undefined} onClick={()=>{setEditing(row);setDrawerName(row.name);}}>Rename</button><button disabled={busy||row.id===currentId&&currentDirty} title={row.id===currentId&&currentDirty?'Finish saving this drawer before deleting it':undefined} onClick={()=>{if(window.confirm(`Delete “${row.name}” and its photo? This cannot be undone.`))void action(async()=>{await deleteDrawer(user.id,row);onDeleted(row.id);});}}>Delete</button></div></article>)}</div>}
 {!loading&&rows.length>0&&!rows.some(r=>r.name.toLowerCase().includes(query.toLowerCase()))&&<p>No drawers match that name.</p>}
 {editing&&<form className="account-notice" onSubmit={e=>{e.preventDefault();void action(async()=>{await renameDrawer(editing,drawerName);setEditing(null);});}}><label>Drawer name<input autoFocus required maxLength={80} value={drawerName} onChange={e=>setDrawerName(e.target.value)}/></label><button className="btn" disabled={busy||!drawerName.trim()}>Save name</button><button type="button" onClick={()=>setEditing(null)}>Cancel</button></form>}
 </section>;
}
