// @vitest-environment jsdom
import { act,renderHook,cleanup as cleanupReact } from '@testing-library/react';
import { afterEach,beforeEach,describe,it,expect,vi } from 'vitest';
import { useWorkspace } from './useWorkspace';
import { ConflictError } from './repository';
import { newDocument } from './document';
const mocks=vi.hoisted(()=>({save:vi.fn(),read:vi.fn(),write:vi.fn(),get:vi.fn(),photo:vi.fn()}));
vi.mock('./drafts',()=>({readDraft:mocks.read,writeDraft:mocks.write}));
vi.mock('./repository',()=>({saveDrawer:mocks.save,getDrawer:mocks.get,photoFile:mocks.photo,cleanup:vi.fn().mockResolvedValue(undefined),ConflictError:class ConflictError extends Error{}}));
beforeEach(()=>{vi.clearAllMocks();sessionStorage.clear();mocks.read.mockResolvedValue(undefined);mocks.write.mockResolvedValue(undefined);mocks.save.mockImplementation(async(_u,id,revision,doc,_photo,path)=>({id,revision:revision+1,document:doc,photo_path:path}));});
afterEach(()=>{cleanupReact();vi.useRealTimers();});
async function ready(user:string|null='a'){vi.useFakeTimers();const hook=renderHook(()=>useWorkspace(user));await act(async()=>{});expect(hook.result.current.ready).toBe(true);return hook;}
async function tick(){await act(async()=>{await vi.advanceTimersByTimeAsync(1100);});}
describe('autosave and recovery',()=>{
 it('debounces edits and only marks the confirmed snapshot saved',async()=>{const {result}=await ready();act(()=>{result.current.change(d=>({...d,name:'Desk'}));result.current.change(d=>({...d,name:'Kitchen'}));});expect(mocks.save).not.toHaveBeenCalled();await tick();expect(mocks.save).toHaveBeenCalledTimes(1);expect(mocks.save.mock.calls[0][3].name).toBe('Kitchen');expect(result.current.draft.dirty).toBe(false);expect(result.current.status).toBe('Saved');});
 it('does not mark unchanged editor reconciliation dirty',async()=>{const {result}=await ready();act(()=>result.current.change(d=>({...d,layout:{...d.layout}})));await tick();expect(mocks.save).not.toHaveBeenCalled();});
 it('retains failed changes and retries without inventing a saved state',async()=>{mocks.save.mockRejectedValueOnce(new Error('Offline'));const {result}=await ready();act(()=>result.current.change(d=>({...d,name:'Desk'})));await tick();expect(result.current.draft.dirty).toBe(true);expect(result.current.status).toBe('Offline');act(()=>result.current.retry());await tick();expect(result.current.draft.dirty).toBe(false);});
 it('serializes writes and saves changes made during an in-flight save',async()=>{let complete:(row:unknown)=>void=()=>{};mocks.save.mockImplementationOnce(()=>new Promise(resolve=>{complete=resolve;}));const {result}=await ready();act(()=>result.current.change(d=>({...d,name:'First'})));await tick();act(()=>result.current.change(d=>({...d,name:'Second'})));await tick();expect(mocks.save).toHaveBeenCalledTimes(1);await act(async()=>complete({id:'drawer',revision:2,photo_path:null}));expect(result.current.draft.dirty).toBe(true);await tick();expect(mocks.save).toHaveBeenCalledTimes(2);expect(mocks.save.mock.calls[1][3].name).toBe('Second');});
 it('preserves guest work before leaving for authentication',async()=>{const {result}=await ready(null);act(()=>result.current.change(d=>({...d,name:'Guest desk'})));await act(async()=>result.current.beforeAuth());expect(sessionStorage.getItem('boxable-import-guest')).toBe('yes');expect(mocks.write).toHaveBeenLastCalledWith('guest',expect.objectContaining({document:expect.objectContaining({name:'Guest desk'})}));expect(mocks.save).not.toHaveBeenCalled();});
 it('restores an unsaved photo replacement and uploads it',async()=>{const photo=new File(['x'],'photo.png',{type:'image/png'});mocks.read.mockResolvedValue({document:newDocument(),photo,id:'drawer',revision:2,photoPath:'a/drawer/old.png',dirty:true,photoChanged:true});await ready();await tick();expect(mocks.save.mock.calls[0][6]).toBe(true);});
});

it('stops on a revision conflict and can save a separate copy',async()=>{mocks.save.mockRejectedValueOnce(new ConflictError());const {result}=await ready();act(()=>result.current.change(d=>({...d,name:'Desk'})));await tick();expect(result.current.conflict).toBe(true);expect(result.current.draft.dirty).toBe(true);act(()=>result.current.retry());await tick();expect(mocks.save).toHaveBeenCalledTimes(1);act(()=>result.current.saveCopy());await tick();expect(mocks.save.mock.calls[1][2]).toBe(0);expect(mocks.save.mock.calls[1][3].name).toBe('Desk (copy)');expect(result.current.draft.dirty).toBe(false);});
it('does not replace current edits with a late drawer fetch',async()=>{let complete:(row:unknown)=>void=()=>{};mocks.get.mockImplementationOnce(()=>new Promise(resolve=>{complete=resolve;}));const {result}=await ready();let opening:Promise<boolean>;act(()=>{opening=result.current.open({id:'other'});});act(()=>result.current.change(d=>({...d,name:'Keep this edit'})));await act(async()=>{complete({id:'other',revision:1,photo_path:null,document:newDocument()});await opening;});expect(result.current.draft.document.name).toBe('Keep this edit');});
